/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace aeb {
namespace config {

struct AutoAebConfig {
  bool aeb_switch;
  float pass_velocity_threshold;
  float close_moving_obstacle_filter_threshold;
  float sector_expand;
  int aeb_period_frequency;
  float ignor_aeb_trigger_in_pdu_lon_distance;
  float ignor_aeb_trigger_in_pdu_lat_distance;
  float ignor_aeb_trigger_in_pdu_timuout_t;
  int chassis_msg_timeout_frames_threshold;
  int control_cmd_msg_timeout_frames_threshold;
  int perception_lms_msg_timeout_frames_threshold;
  int perception_msg_timeout_frames_threshold;
  int decision_msg_timeout_frames_threshold;
  int planning_msg_timeout_frames_threshold;
  int prediction_msg_timeout_frames_threshold;
  int canbus_wheel_msg_timeout_frames_threshold;
  int localization_msg_timeout_frames_threshold;
  int baselink_in_odom_msg_timeout_frames_threshold;
  int freespace_msg_timeout_frames_threshold;
  float strict_timeout_check;
  float lenient_timeout_check;
  int lidar_obstacle_lost_threshold;
  float relative_distance_threshold;
  float relative_speed_threshold;
  float double_check_imu_threshold;
  float obstacle_collision_ttc;
};

void InitAutoAebConfig(const Json::Value &input_json, AutoAebConfig &dest);

}  // namespace config
}  // namespace aeb
}  // namespace neodrive
