/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace aeb {
namespace config {

struct AutoDynamicAebConfig {
  struct DefaultGroup {
    float lateral_expand_dist;
    float longitudianl_expand_dist;
    float stop_safe_dist;
    float polygon_distance_step;
    float polygon_distance_threshold;
  };
  DefaultGroup default_group;
};

void InitAutoDynamicAebConfig(const Json::Value &input_json,
                              AutoDynamicAebConfig &dest);
}  // namespace config
}  // namespace aeb
}  // namespace neodrive
