/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#include "config/auto_dynamic_aeb_config.h"

namespace neodrive {
namespace aeb {
namespace config {

void InitAutoDynamicAebConfig(const Json::Value &input_json,
                              AutoDynamicAebConfig &dest) {
  dest.default_group.lateral_expand_dist =
      input_json["default_group"][0]["lateral_expand_dist"][0].asDouble();
  dest.default_group.longitudianl_expand_dist =
      input_json["default_group"][1]["longitudianl_expand_dist"][0].asDouble();
  dest.default_group.stop_safe_dist =
      input_json["default_group"][2]["stop_safe_dist"][0].asDouble();
  dest.default_group.polygon_distance_step =
      input_json["default_group"][3]["polygon_distance_step"][0].asDouble();
  dest.default_group.polygon_distance_threshold =
      input_json["default_group"][4]["polygon_distance_threshold"][0]
          .asDouble();
};
}  // namespace config
}  // namespace aeb
}  // namespace neodrive
