/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace world_model {
namespace config {

struct AutoWorldModelConfig {
  int odom_pose_frequency;
  int utm_pose_frequency;
  bool ego_kinematics_estimation;
  float localization_error_code_obsolete_time;
};

void InitAutoWorldModelConfig(const Json::Value &input_json,
                              AutoWorldModelConfig &dest);

}  // namespace config
}  // namespace world_model
}  // namespace neodrive
