/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#include "config/auto_world_model_config.h"

namespace neodrive {
namespace world_model {
namespace config {

void InitAutoWorldModelConfig(const Json::Value &input_json,
                              AutoWorldModelConfig &dest) {
  dest.odom_pose_frequency = input_json["odom_pose_frequency"].asInt();
  dest.utm_pose_frequency = input_json["utm_pose_frequency"].asInt();
  dest.ego_kinematics_estimation =
      input_json["ego_kinematics_estimation"].asBool();
  dest.localization_error_code_obsolete_time =
      input_json["localization_error_code_obsolete_time"].asDouble();
}

}  // namespace config
}  // namespace world_model
}  // namespace neodrive
