/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#include "config/auto_fsm_config.h"

namespace neodrive {
namespace planning {
namespace config {

void InitAutoFsmConfig(const Json::Value &input_json, AutoFsmConfig &dest) {
  dest.fsm_states_pool.planning_init =
      input_json["fsm_states_pool"]["PLANNING_INIT"].asString();
  dest.fsm_states_pool.planning_fail =
      input_json["fsm_states_pool"]["PLANNING_FAIL"].asString();
  dest.fsm_states_pool.planning_cruise =
      input_json["fsm_states_pool"]["PLANNING_CRUISE"].asString();
  dest.fsm_states_pool.planning_abnormal =
      input_json["fsm_states_pool"]["PLANNING_ABNORMAL"].asString();
}

}  // namespace config
}  // namespace planning
}  // namespace neodrive
