/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace planning {
namespace config {

struct AutoFsmConfig {
  struct FsmStatesPool {
    std::string planning_init;
    std::string planning_fail;
    std::string planning_cruise;
    std::string planning_abnormal;
  };
  FsmStatesPool fsm_states_pool;
};

void InitAutoFsmConfig(const Json::Value &input_json, AutoFsmConfig &dest);

}  // namespace config
}  // namespace planning
}  // namespace neodrive
