/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#include "config/auto_ego_attribuate.h"

namespace neodrive {
namespace planning_rl {
namespace config {

void InitAutoEgoAttribuate(const Json::Value &input_json,
                           AutoEgoAttribuate &dest) {
  dest.ego.car_type = input_json["ego"]["car_type"].asString();
  dest.ego.ego_length = input_json["ego"]["ego_length"].asDouble();
  dest.ego.ego_width = input_json["ego"]["ego_width"].asDouble();
  dest.ego.ego_center.x = input_json["ego"]["ego_center"]["x"].asDouble();
  dest.ego.ego_center.y = input_json["ego"]["ego_center"]["y"].asDouble();
  dest.ego.ego_speed = input_json["ego"]["ego_speed"].asDouble();
  dest.ego.ego_speed_lon = input_json["ego"]["ego_speed_lon"].asDouble();
  dest.ego.ego_speed_lat = input_json["ego"]["ego_speed_lat"].asDouble();
  dest.ego.ego_heading = input_json["ego"]["ego_heading"].asDouble();
  dest.ego.ego_acc = input_json["ego"]["ego_acc"].asInt();
  dest.ego.ego_react_time = input_json["ego"]["ego_react_time"].asDouble();
  dest.ego.ego_max_accel_lon =
      input_json["ego"]["ego_max_accel_lon"].asDouble();
  dest.ego.ego_max_brake_lon =
      input_json["ego"]["ego_max_brake_lon"].asDouble();
  dest.ego.ego_min_brake_lon =
      input_json["ego"]["ego_min_brake_lon"].asDouble();
  dest.ego.ego_max_accel_lat =
      input_json["ego"]["ego_max_accel_lat"].asDouble();
  dest.ego.ego_max_brake_lat =
      input_json["ego"]["ego_max_brake_lat"].asDouble();
  dest.ego.ego_min_brake_lat =
      input_json["ego"]["ego_min_brake_lat"].asDouble();
  dest.ego.ego_j_min = input_json["ego"]["ego_j_min"].asDouble();
  dest.ego.ego_j_max = input_json["ego"]["ego_j_max"].asDouble();
  dest.ego.min_lon_distance = input_json["ego"]["min_lon_distance"].asDouble();
  dest.ego.min_lat_distance = input_json["ego"]["min_lat_distance"].asDouble();
  dest.agent_vehicle.car_type =
      input_json["agent_vehicle"]["car_type"].asString();
  dest.agent_vehicle.agent_length =
      input_json["agent_vehicle"]["agent_length"].asDouble();
  dest.agent_vehicle.agent_width =
      input_json["agent_vehicle"]["agent_width"].asDouble();
  dest.agent_vehicle.agent_center.x =
      input_json["agent_vehicle"]["agent_center"]["x"].asDouble();
  dest.agent_vehicle.agent_center.y =
      input_json["agent_vehicle"]["agent_center"]["y"].asDouble();
  dest.agent_vehicle.agent_speed =
      input_json["agent_vehicle"]["agent_speed"].asDouble();
  dest.agent_vehicle.agent_speed_lon =
      input_json["agent_vehicle"]["agent_speed_lon"].asDouble();
  dest.agent_vehicle.agent_speed_lat =
      input_json["agent_vehicle"]["agent_speed_lat"].asDouble();
  dest.agent_vehicle.agent_heading =
      input_json["agent_vehicle"]["agent_heading"].asDouble();
  dest.agent_vehicle.agent_acc =
      input_json["agent_vehicle"]["agent_acc"].asDouble();
  dest.agent_vehicle.agent_react_time =
      input_json["agent_vehicle"]["agent_react_time"].asDouble();
  dest.agent_vehicle.agent_max_accel_lon =
      input_json["agent_vehicle"]["agent_max_accel_lon"].asDouble();
  dest.agent_vehicle.agent_max_brake_lon =
      input_json["agent_vehicle"]["agent_max_brake_lon"].asInt();
  dest.agent_vehicle.agent_min_brake_lon =
      input_json["agent_vehicle"]["agent_min_brake_lon"].asInt();
  dest.agent_vehicle.agent_max_accel_lat =
      input_json["agent_vehicle"]["agent_max_accel_lat"].asDouble();
  dest.agent_vehicle.agent_max_brake_lat =
      input_json["agent_vehicle"]["agent_max_brake_lat"].asDouble();
  dest.agent_vehicle.agent_min_brake_lat =
      input_json["agent_vehicle"]["agent_min_brake_lat"].asDouble();
  dest.agent_vehicle.agent_j_max =
      input_json["agent_vehicle"]["agent_j_max"].asDouble();
  dest.agent_vehicle.agent_j_min =
      input_json["agent_vehicle"]["agent_j_min"].asDouble();
  dest.agent_vehicle.min_lon_distance =
      input_json["agent_vehicle"]["min_lon_distance"].asDouble();
  dest.agent_vehicle.min_lat_distance =
      input_json["agent_vehicle"]["min_lat_distance"].asDouble();
  dest.agent_truck.car_type = input_json["agent_truck"]["car_type"].asString();
  dest.agent_truck.agent_length =
      input_json["agent_truck"]["agent_length"].asDouble();
  dest.agent_truck.agent_width =
      input_json["agent_truck"]["agent_width"].asDouble();
  dest.agent_truck.agent_center.x =
      input_json["agent_truck"]["agent_center"]["x"].asDouble();
  dest.agent_truck.agent_center.y =
      input_json["agent_truck"]["agent_center"]["y"].asDouble();
  dest.agent_truck.agent_speed =
      input_json["agent_truck"]["agent_speed"].asDouble();
  dest.agent_truck.agent_speed_lon =
      input_json["agent_truck"]["agent_speed_lon"].asDouble();
  dest.agent_truck.agent_speed_lat =
      input_json["agent_truck"]["agent_speed_lat"].asDouble();
  dest.agent_truck.agent_heading =
      input_json["agent_truck"]["agent_heading"].asDouble();
  dest.agent_truck.agent_acc =
      input_json["agent_truck"]["agent_acc"].asDouble();
  dest.agent_truck.agent_react_time =
      input_json["agent_truck"]["agent_react_time"].asDouble();
  dest.agent_truck.agent_max_accel_lon =
      input_json["agent_truck"]["agent_max_accel_lon"].asDouble();
  dest.agent_truck.agent_max_brake_lon =
      input_json["agent_truck"]["agent_max_brake_lon"].asDouble();
  dest.agent_truck.agent_min_brake_lon =
      input_json["agent_truck"]["agent_min_brake_lon"].asInt();
  dest.agent_truck.agent_max_accel_lat =
      input_json["agent_truck"]["agent_max_accel_lat"].asDouble();
  dest.agent_truck.agent_max_brake_lat =
      input_json["agent_truck"]["agent_max_brake_lat"].asDouble();
  dest.agent_truck.agent_min_brake_lat =
      input_json["agent_truck"]["agent_min_brake_lat"].asDouble();
  dest.agent_truck.agent_j_max =
      input_json["agent_truck"]["agent_j_max"].asDouble();
  dest.agent_truck.agent_j_min =
      input_json["agent_truck"]["agent_j_min"].asDouble();
  dest.agent_truck.min_lon_distance =
      input_json["agent_truck"]["min_lon_distance"].asDouble();
  dest.agent_truck.min_lat_distance =
      input_json["agent_truck"]["min_lat_distance"].asDouble();
  dest.agent_pedestrian.car_type =
      input_json["agent_pedestrian"]["car_type"].asString();
  dest.agent_pedestrian.agent_length =
      input_json["agent_pedestrian"]["agent_length"].asDouble();
  dest.agent_pedestrian.agent_width =
      input_json["agent_pedestrian"]["agent_width"].asDouble();
  dest.agent_pedestrian.agent_center.x =
      input_json["agent_pedestrian"]["agent_center"]["x"].asDouble();
  dest.agent_pedestrian.agent_center.y =
      input_json["agent_pedestrian"]["agent_center"]["y"].asDouble();
  dest.agent_pedestrian.agent_speed =
      input_json["agent_pedestrian"]["agent_speed"].asDouble();
  dest.agent_pedestrian.agent_speed_lon =
      input_json["agent_pedestrian"]["agent_speed_lon"].asDouble();
  dest.agent_pedestrian.agent_speed_lat =
      input_json["agent_pedestrian"]["agent_speed_lat"].asDouble();
  dest.agent_pedestrian.agent_heading =
      input_json["agent_pedestrian"]["agent_heading"].asDouble();
  dest.agent_pedestrian.agent_acc =
      input_json["agent_pedestrian"]["agent_acc"].asDouble();
  dest.agent_pedestrian.agent_react_time =
      input_json["agent_pedestrian"]["agent_react_time"].asDouble();
  dest.agent_pedestrian.agent_max_accel_lon =
      input_json["agent_pedestrian"]["agent_max_accel_lon"].asDouble();
  dest.agent_pedestrian.agent_max_brake_lon =
      input_json["agent_pedestrian"]["agent_max_brake_lon"].asDouble();
  dest.agent_pedestrian.agent_min_brake_lon =
      input_json["agent_pedestrian"]["agent_min_brake_lon"].asDouble();
  dest.agent_pedestrian.agent_max_accel_lat =
      input_json["agent_pedestrian"]["agent_max_accel_lat"].asDouble();
  dest.agent_pedestrian.agent_max_brake_lat =
      input_json["agent_pedestrian"]["agent_max_brake_lat"].asDouble();
  dest.agent_pedestrian.agent_min_brake_lat =
      input_json["agent_pedestrian"]["agent_min_brake_lat"].asDouble();
  dest.agent_pedestrian.agent_j_max =
      input_json["agent_pedestrian"]["agent_j_max"].asDouble();
  dest.agent_pedestrian.agent_j_min =
      input_json["agent_pedestrian"]["agent_j_min"].asDouble();
  dest.agent_pedestrian.min_lon_distance =
      input_json["agent_pedestrian"]["min_lon_distance"].asDouble();
  dest.agent_pedestrian.min_lat_distance =
      input_json["agent_pedestrian"]["min_lat_distance"].asDouble();
  dest.agent_tricycle.car_type =
      input_json["agent_tricycle"]["car_type"].asString();
  dest.agent_tricycle.agent_length =
      input_json["agent_tricycle"]["agent_length"].asDouble();
  dest.agent_tricycle.agent_width =
      input_json["agent_tricycle"]["agent_width"].asDouble();
  dest.agent_tricycle.agent_center.x =
      input_json["agent_tricycle"]["agent_center"]["x"].asDouble();
  dest.agent_tricycle.agent_center.y =
      input_json["agent_tricycle"]["agent_center"]["y"].asDouble();
  dest.agent_tricycle.agent_speed =
      input_json["agent_tricycle"]["agent_speed"].asDouble();
  dest.agent_tricycle.agent_speed_lon =
      input_json["agent_tricycle"]["agent_speed_lon"].asDouble();
  dest.agent_tricycle.agent_speed_lat =
      input_json["agent_tricycle"]["agent_speed_lat"].asDouble();
  dest.agent_tricycle.agent_heading =
      input_json["agent_tricycle"]["agent_heading"].asDouble();
  dest.agent_tricycle.agent_acc =
      input_json["agent_tricycle"]["agent_acc"].asDouble();
  dest.agent_tricycle.agent_react_time =
      input_json["agent_tricycle"]["agent_react_time"].asDouble();
  dest.agent_tricycle.agent_max_accel_lon =
      input_json["agent_tricycle"]["agent_max_accel_lon"].asDouble();
  dest.agent_tricycle.agent_max_brake_lon =
      input_json["agent_tricycle"]["agent_max_brake_lon"].asDouble();
  dest.agent_tricycle.agent_min_brake_lon =
      input_json["agent_tricycle"]["agent_min_brake_lon"].asDouble();
  dest.agent_tricycle.agent_max_accel_lat =
      input_json["agent_tricycle"]["agent_max_accel_lat"].asDouble();
  dest.agent_tricycle.agent_max_brake_lat =
      input_json["agent_tricycle"]["agent_max_brake_lat"].asDouble();
  dest.agent_tricycle.agent_min_brake_lat =
      input_json["agent_tricycle"]["agent_min_brake_lat"].asDouble();
  dest.agent_tricycle.agent_j_max =
      input_json["agent_tricycle"]["agent_j_max"].asDouble();
  dest.agent_tricycle.agent_j_min =
      input_json["agent_tricycle"]["agent_j_min"].asDouble();
  dest.agent_tricycle.min_lon_distance =
      input_json["agent_tricycle"]["min_lon_distance"].asDouble();
  dest.agent_tricycle.min_lat_distance =
      input_json["agent_tricycle"]["min_lat_distance"].asDouble();
  dest.agent_bicycle.car_type =
      input_json["agent_bicycle"]["car_type"].asString();
  dest.agent_bicycle.agent_length =
      input_json["agent_bicycle"]["agent_length"].asDouble();
  dest.agent_bicycle.agent_width =
      input_json["agent_bicycle"]["agent_width"].asDouble();
  dest.agent_bicycle.agent_center.x =
      input_json["agent_bicycle"]["agent_center"]["x"].asDouble();
  dest.agent_bicycle.agent_center.y =
      input_json["agent_bicycle"]["agent_center"]["y"].asDouble();
  dest.agent_bicycle.agent_speed =
      input_json["agent_bicycle"]["agent_speed"].asDouble();
  dest.agent_bicycle.agent_speed_lon =
      input_json["agent_bicycle"]["agent_speed_lon"].asDouble();
  dest.agent_bicycle.agent_speed_lat =
      input_json["agent_bicycle"]["agent_speed_lat"].asDouble();
  dest.agent_bicycle.agent_heading =
      input_json["agent_bicycle"]["agent_heading"].asDouble();
  dest.agent_bicycle.agent_acc =
      input_json["agent_bicycle"]["agent_acc"].asDouble();
  dest.agent_bicycle.agent_react_time =
      input_json["agent_bicycle"]["agent_react_time"].asDouble();
  dest.agent_bicycle.agent_max_accel_lon =
      input_json["agent_bicycle"]["agent_max_accel_lon"].asDouble();
  dest.agent_bicycle.agent_max_brake_lon =
      input_json["agent_bicycle"]["agent_max_brake_lon"].asDouble();
  dest.agent_bicycle.agent_min_brake_lon =
      input_json["agent_bicycle"]["agent_min_brake_lon"].asDouble();
  dest.agent_bicycle.agent_max_accel_lat =
      input_json["agent_bicycle"]["agent_max_accel_lat"].asDouble();
  dest.agent_bicycle.agent_max_brake_lat =
      input_json["agent_bicycle"]["agent_max_brake_lat"].asDouble();
  dest.agent_bicycle.agent_min_brake_lat =
      input_json["agent_bicycle"]["agent_min_brake_lat"].asDouble();
  dest.agent_bicycle.agent_j_max =
      input_json["agent_bicycle"]["agent_j_max"].asDouble();
  dest.agent_bicycle.agent_j_min =
      input_json["agent_bicycle"]["agent_j_min"].asDouble();
  dest.agent_bicycle.min_lon_distance =
      input_json["agent_bicycle"]["min_lon_distance"].asDouble();
  dest.agent_bicycle.min_lat_distance =
      input_json["agent_bicycle"]["min_lat_distance"].asDouble();
  dest.agent_unmovable.car_type =
      input_json["agent_unmovable"]["car_type"].asString();
  dest.agent_unmovable.agent_length =
      input_json["agent_unmovable"]["agent_length"].asDouble();
  dest.agent_unmovable.agent_width =
      input_json["agent_unmovable"]["agent_width"].asDouble();
  dest.agent_unmovable.agent_center.x =
      input_json["agent_unmovable"]["agent_center"]["x"].asDouble();
  dest.agent_unmovable.agent_center.y =
      input_json["agent_unmovable"]["agent_center"]["y"].asDouble();
  dest.agent_unmovable.agent_speed =
      input_json["agent_unmovable"]["agent_speed"].asDouble();
  dest.agent_unmovable.agent_speed_lon =
      input_json["agent_unmovable"]["agent_speed_lon"].asDouble();
  dest.agent_unmovable.agent_speed_lat =
      input_json["agent_unmovable"]["agent_speed_lat"].asDouble();
  dest.agent_unmovable.agent_heading =
      input_json["agent_unmovable"]["agent_heading"].asDouble();
  dest.agent_unmovable.agent_acc =
      input_json["agent_unmovable"]["agent_acc"].asDouble();
  dest.agent_unmovable.agent_react_time =
      input_json["agent_unmovable"]["agent_react_time"].asDouble();
  dest.agent_unmovable.agent_max_accel_lon =
      input_json["agent_unmovable"]["agent_max_accel_lon"].asDouble();
  dest.agent_unmovable.agent_max_brake_lon =
      input_json["agent_unmovable"]["agent_max_brake_lon"].asDouble();
  dest.agent_unmovable.agent_min_brake_lon =
      input_json["agent_unmovable"]["agent_min_brake_lon"].asDouble();
  dest.agent_unmovable.agent_max_accel_lat =
      input_json["agent_unmovable"]["agent_max_accel_lat"].asDouble();
  dest.agent_unmovable.agent_max_brake_lat =
      input_json["agent_unmovable"]["agent_max_brake_lat"].asDouble();
  dest.agent_unmovable.agent_min_brake_lat =
      input_json["agent_unmovable"]["agent_min_brake_lat"].asDouble();
  dest.agent_unmovable.agent_j_max =
      input_json["agent_unmovable"]["agent_j_max"].asDouble();
  dest.agent_unmovable.agent_j_min =
      input_json["agent_unmovable"]["agent_j_min"].asDouble();
  dest.agent_unmovable.min_lon_distance =
      input_json["agent_unmovable"]["min_lon_distance"].asDouble();
  dest.agent_unmovable.min_lat_distance =
      input_json["agent_unmovable"]["min_lat_distance"].asDouble();
}

}  // namespace config
}  // namespace planning_rl
}  // namespace neodrive
