/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#include "config/auto_rl_model_config.h"

namespace neodrive {
namespace planning_rl {
namespace config {

void InitAutoRlModelConfig(const Json::Value &input_json,
                           AutoRlModelConfig &dest) {
  dest.imitation_learning.model_input_shape.frame_num =
      input_json["imitation_learning"]["model_input_shape"]["frame_num"]
          .asInt();
  dest.imitation_learning.model_input_shape.dimension =
      input_json["imitation_learning"]["model_input_shape"]["dimension"]
          .asInt();
  dest.imitation_learning.model_path =
      input_json["imitation_learning"]["model_path"].asString();
  dest.feature_net.model_path =
      input_json["feature_net"]["model_path"].asString();
  dest.two_stage_net.model_path =
      input_json["two_stage_net"]["model_path"].asString();
  dest.urban_driver.model_path =
      input_json["urban_driver"]["model_path"].asString();
}

}  // namespace config
}  // namespace planning_rl
}  // namespace neodrive
