/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace planning_rl {
namespace config {

struct AutoRlModelConfig {
  struct ImitationLearning {
    struct ModelInputShape {
      int frame_num;
      int dimension;
    };
    ModelInputShape model_input_shape;
    std::string model_path;
  };
  ImitationLearning imitation_learning;
  struct FeatureNet {
    std::string model_path;
  };
  FeatureNet feature_net;
  struct TwoStageNet {
    std::string model_path;
  };
  TwoStageNet two_stage_net;
  struct UrbanDriver {
    std::string model_path;
  };
  UrbanDriver urban_driver;
};

void InitAutoRlModelConfig(const Json::Value &input_json,
                           AutoRlModelConfig &dest);

}  // namespace config
}  // namespace planning_rl
}  // namespace neodrive
