/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace planning_rl {
namespace config {

struct AutoPostPredict {
  struct RescaleActionParas {
    float max_acc;
    float min_brake;
    float max_deta_x;
    float max_deta_y;
    float min_deta_x;
    float min_deta_y;
    float max_theta;
    float min_theta;
    float max_time;
    float max_speed;
    float max_curvature;
  };
  RescaleActionParas rescale_action_paras;
};

void InitAutoPostPredict(const Json::Value &input_json, AutoPostPredict &dest);

}  // namespace config
}  // namespace planning_rl
}  // namespace neodrive
