/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace planning_rl {
namespace config {

struct AutoTopicsConfig {
  struct Topics {
    std::string key;
    std::string topic;
    int queue_size;
    std::string type;
  };
  std::unordered_map<std::string, Topics> topics;
};

void InitAutoTopicsConfig(const Json::Value &input_json,
                          AutoTopicsConfig &dest);

}  // namespace config
}  // namespace planning_rl
}  // namespace neodrive
