/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#pragma once

#include <jsoncpp/json/json.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace neodrive {
namespace config_server {
namespace config {

struct AutoConfigServerConfig {
  int config_server_period_frequency;
  std::string server_url;
  std::string server_path;
  int server_port;
  int connection_loss_threshold;
  int connection_security_level;
  float send_empty_data_time_threshold;
};

void InitAutoConfigServerConfig(const Json::Value &input_json,
                                AutoConfigServerConfig &dest);

}  // namespace config
}  // namespace config_server
}  // namespace neodrive
