/**
 * @brief this file is auto-generated by scripts/json_to_cpp.py. Do not edit!!!
 */

#include "config/auto_config_server_config.h"

namespace neodrive {
namespace config_server {
namespace config {

void InitAutoConfigServerConfig(const Json::Value &input_json,
                                AutoConfigServerConfig &dest) {
  dest.config_server_period_frequency =
      input_json["config_server_period_frequency"].asInt();
  dest.server_url = input_json["server_url"].asString();
  dest.server_path = input_json["server_path"].asString();
  dest.server_port = input_json["server_port"].asInt();
  dest.connection_loss_threshold =
      input_json["connection_loss_threshold"].asInt();
  dest.connection_security_level =
      input_json["connection_security_level"].asInt();
  dest.send_empty_data_time_threshold =
      input_json["send_empty_data_time_threshold"].asDouble();
}

}  // namespace config
}  // namespace config_server
}  // namespace neodrive
