set(CEREAL_ROOT "${GEARS_ARCH}" CACHE PATH "PROTOBUF_ROOT")
set(CEREAL_INCLUDE_DIR ${PROTOBUF_ROOT}/include/cereal CACHE INTERNAL "PROTOBUF_INCLUDE_DIR")

include_directories(${CEREAL_INCLUDE_DIR})
message(STATUS "CEREAL_INCLUDE_DIR:" ${CEREAL_INCLUDE_DIR})