# OSQP library and headers
set(OSQP_FOUND 1 CACHE INTERNAL "OSQP_FOUND")
set(OSQP_ROOT "${GEARS_ARCH}" CACHE PATH "OSQP_ROOT")
set(OSQP_INCLUDE_DIRS ${OSQP_ROOT}/include/osqp CACHE INTERNAL "OSQP_INCLUDE_DIRS")
set(OSQP_LIBRARY_DIRS ${OSQP_ROOT}/lib CACHE INTERNAL "OSQP_LIBRARY_DIRS")
file(GLOB LIBRARIES "${OSQP_LIBRARY_DIRS}/libosqp*.so")
set(OSQP_LIBRARIES ${LIBRARIES} CACHE INTERNAL "OSQP_LIBRARIES")

include_directories(${OSQP_INCLUDE_DIRS})
link_directories(${OSQP_LIBRARY_DIRS})
message(STATUS "OSQP_INCLUDE_DIRS: ${OSQP_INCLUDE_DIRS}")
message(STATUS "OSQP_LIBRARY_DIRS: ${OSQP_LIBRARY_DIRS}")
message(STATUS "OSQP_LIBRARIES: ${OSQP_LIBRARIES}")
